import 'dart:io';

void main() {
  final Directory dir = Directory('lib');
  if (!dir.existsSync()) return; // Fail silently so we don't break the user's git commit

  int setStateCount = 0;
  int valueNotifierCount = 0;
  int repaintBoundaryCount = 0;
  int transactionCount = 0;
  int incrementCount = 0;
  final List<String> thoughts = <String>[];

  for (final FileSystemEntity entity in dir.listSync(recursive: true)) {
    if (entity is! File || !entity.path.endsWith('.dart')) continue;

    try {
      final List<String> lines = entity.readAsLinesSync();
      for (int i = 0; i < lines.length; i++) {
        final String line = lines[i].trim();
        if (line.isEmpty || line.startsWith('//')) continue;

        if (line.contains('setState(')) setStateCount++;
        if (line.contains('ValueNotifier')) valueNotifierCount++;
        if (line.contains('RepaintBoundary')) repaintBoundaryCount++;
        if (line.contains('runTransaction')) transactionCount++;
        if (line.contains('FieldValue.increment')) incrementCount++;

        if (line.contains('// @AETHER:')) {
          final String note = line.substring(line.indexOf('// @AETHER:') + 11).trim();
          thoughts.add('- **${entity.uri.pathSegments.last}** (Line ${i + 1}): $note');
        }
      }
    } catch (_) {
      // Catch read errors (e.g. encoding issues) and skip gracefully
    }
  }

  final File telemetryFile = File('AETHER_TELEMETRY.md');
  final StringBuffer output = StringBuffer('# Aether Automated Telemetry Report\n\n')
    ..writeln('> Auto-generated by the pre-commit "Flight Recorder".\n')
    ..writeln('## 1. Architectural Fingerprint');
  if (transactionCount > 0 || incrementCount > 0) {
    output.writeln(
      '✅ Atomic operations detected (`runTransaction`: $transactionCount, `increment`: $incrementCount)',
    );
  } else {
    output.writeln('❌ No atomic operations detected.');
  }

  output
    ..writeln('\n### UI Performance')
    ..writeln(
      '- `setState`: $setStateCount | `ValueNotifier`: $valueNotifierCount | `RepaintBoundary`: $repaintBoundaryCount',
    );

  if (valueNotifierCount > 0 || repaintBoundaryCount > 0) {
    output.writeln('✅ Targeted repaints detected.');
  } else if (setStateCount > 3) {
    output.writeln('⚠️ High `setState` usage without localized rebuilds.');
  }

  output.writeln('\n## 2. Developer Thought Log');
  if (thoughts.isNotEmpty) {
    for (final String thought in thoughts) {
      output.writeln(thought);
    }
  } else {
    output.writeln('*No inline `// @AETHER:` comments found.*');
  }

  try {
    telemetryFile.writeAsStringSync(output.toString());
  } catch (_) {
    // Failsafe
  }
}
